# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiS.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(796, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(27, 420, 721, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(360, 20, 20, 241))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(600, 450, 3, 61))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(460, 450, 3, 61))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(480, 440, 51, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(610, 440, 51, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 440, 91, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(10, 280, 721, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 440, 91, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(459, 320, 3, 61))
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(569, 290, 62, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(140, 300, 62, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(309, 320, 3, 61))
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(350, 290, 71, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(240, 450, 3, 61))
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.dial = QtGui.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(360, 330, 50, 64))
        self.dial.setMinimum(0)
        self.dial.setProperty("value", 50)
        self.dial.setSliderPosition(50)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 180, 311, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(150, 240, 71, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(180, 20, 20, 141))
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.line_11 = QtGui.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(550, 10, 20, 181))
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.dial_2 = QtGui.QDial(self.centralwidget)
        self.dial_2.setGeometry(QtCore.QRect(540, 210, 50, 64))
        self.dial_2.setMinimum(0)
        self.dial_2.setProperty("value", 50)
        self.dial_2.setSliderPosition(50)
        self.dial_2.setTracking(False)
        self.dial_2.setOrientation(QtCore.Qt.Vertical)
        self.dial_2.setObjectName(_fromUtf8("dial_2"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 20, 62, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(250, 20, 62, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(440, 20, 62, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(630, 20, 62, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalSlider = QtGui.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(40, 320, 21, 81))
        self.verticalSlider.setProperty("value", 40)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.verticalSlider_2 = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_2.setGeometry(QtCore.QRect(90, 320, 21, 81))
        self.verticalSlider_2.setProperty("value", 40)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName(_fromUtf8("verticalSlider_2"))
        self.verticalSlider_3 = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_3.setGeometry(QtCore.QRect(130, 320, 21, 81))
        self.verticalSlider_3.setProperty("value", 40)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName(_fromUtf8("verticalSlider_3"))
        self.verticalSlider_4 = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_4.setGeometry(QtCore.QRect(170, 320, 21, 81))
        self.verticalSlider_4.setProperty("value", 40)
        self.verticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_4.setObjectName(_fromUtf8("verticalSlider_4"))
        self.verticalSlider_5 = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_5.setGeometry(QtCore.QRect(210, 320, 21, 81))
        self.verticalSlider_5.setProperty("value", 40)
        self.verticalSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_5.setObjectName(_fromUtf8("verticalSlider_5"))
        self.verticalSlider_6 = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_6.setGeometry(QtCore.QRect(400, 440, 28, 91))
        self.verticalSlider_6.setProperty("value", 65)
        self.verticalSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_6.setObjectName(_fromUtf8("verticalSlider_6"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 480, 90, 28))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.dial_5 = QtGui.QDial(self.centralwidget)
        self.dial_5.setGeometry(QtCore.QRect(60, 210, 50, 64))
        self.dial_5.setObjectName(_fromUtf8("dial_5"))
        self.dial_6 = QtGui.QDial(self.centralwidget)
        self.dial_6.setGeometry(QtCore.QRect(260, 210, 50, 64))
        self.dial_6.setObjectName(_fromUtf8("dial_6"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(40, 400, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(170, 400, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(130, 400, 16, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(130, 400, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(90, 400, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(210, 400, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.dial_8 = QtGui.QDial(self.centralwidget)
        self.dial_8.setGeometry(QtCore.QRect(120, 110, 61, 61))
        self.dial_8.setMaximum(4)
        self.dial_8.setObjectName(_fromUtf8("dial_8"))
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(270, 200, 41, 21))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.lcdNumber_2 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(70, 200, 41, 21))
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.verticalSlider_7 = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_7.setGeometry(QtCore.QRect(20, 20, 28, 131))
        self.verticalSlider_7.setProperty("value", 50)
        self.verticalSlider_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_7.setObjectName(_fromUtf8("verticalSlider_7"))
        self.dial_7 = QtGui.QDial(self.centralwidget)
        self.dial_7.setGeometry(QtCore.QRect(60, 90, 50, 64))
        self.dial_7.setMinimum(-50)
        self.dial_7.setMaximum(50)
        self.dial_7.setObjectName(_fromUtf8("dial_7"))
        self.dial_23 = QtGui.QDial(self.centralwidget)
        self.dial_23.setGeometry(QtCore.QRect(20, 460, 50, 64))
        self.dial_23.setObjectName(_fromUtf8("dial_23"))
        self.dial_25 = QtGui.QDial(self.centralwidget)
        self.dial_25.setGeometry(QtCore.QRect(90, 460, 50, 64))
        self.dial_25.setObjectName(_fromUtf8("dial_25"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(20, 520, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setTextFormat(QtCore.Qt.LogText)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(100, 520, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setTextFormat(QtCore.Qt.LogText)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(270, 260, 62, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(60, 260, 62, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lcdNumber_3 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(510, 317, 41, 21))
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(500, 377, 62, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.dial_26 = QtGui.QDial(self.centralwidget)
        self.dial_26.setGeometry(QtCore.QRect(500, 330, 50, 61))
        self.dial_26.setObjectName(_fromUtf8("dial_26"))
        self.lcdNumber_4 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setGeometry(QtCore.QRect(640, 320, 41, 21))
        self.lcdNumber_4.setObjectName(_fromUtf8("lcdNumber_4"))
        self.dial_27 = QtGui.QDial(self.centralwidget)
        self.dial_27.setGeometry(QtCore.QRect(630, 333, 50, 61))
        self.dial_27.setObjectName(_fromUtf8("dial_27"))
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(60, 110, 62, 20))
        self.label_26.setText(_fromUtf8(""))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(250, 400, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalSlider_11 = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_11.setGeometry(QtCore.QRect(250, 320, 21, 81))
        self.verticalSlider_11.setProperty("value", 40)
        self.verticalSlider_11.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_11.setObjectName(_fromUtf8("verticalSlider_11"))
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(530, 260, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.lcdNumber_5 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_5.setGeometry(QtCore.QRect(70, 60, 41, 21))
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.label_29 = QtGui.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(10, 160, 62, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(140, 170, 62, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(70, 150, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(250, 150, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_32.setFont(font)
        self.label_32.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(320, 170, 62, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.lcdNumber_6 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_6.setGeometry(QtCore.QRect(250, 60, 41, 21))
        self.lcdNumber_6.setObjectName(_fromUtf8("lcdNumber_6"))
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(240, 110, 62, 20))
        self.label_34.setText(_fromUtf8(""))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(190, 160, 62, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.dial_9 = QtGui.QDial(self.centralwidget)
        self.dial_9.setGeometry(QtCore.QRect(240, 90, 50, 64))
        self.dial_9.setMinimum(-50)
        self.dial_9.setMaximum(50)
        self.dial_9.setObjectName(_fromUtf8("dial_9"))
        self.verticalSlider_8 = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_8.setGeometry(QtCore.QRect(200, 20, 28, 131))
        self.verticalSlider_8.setProperty("value", 50)
        self.verticalSlider_8.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_8.setObjectName(_fromUtf8("verticalSlider_8"))
        self.label_36 = QtGui.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(440, 150, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_36.setFont(font)
        self.label_36.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.lcdNumber_7 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_7.setGeometry(QtCore.QRect(440, 60, 41, 21))
        self.lcdNumber_7.setObjectName(_fromUtf8("lcdNumber_7"))
        self.label_37 = QtGui.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(430, 110, 62, 20))
        self.label_37.setText(_fromUtf8(""))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(380, 160, 62, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.dial_11 = QtGui.QDial(self.centralwidget)
        self.dial_11.setGeometry(QtCore.QRect(430, 90, 50, 64))
        self.dial_11.setMinimum(-50)
        self.dial_11.setMaximum(50)
        self.dial_11.setObjectName(_fromUtf8("dial_11"))
        self.verticalSlider_9 = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_9.setGeometry(QtCore.QRect(390, 20, 28, 131))
        self.verticalSlider_9.setProperty("value", 50)
        self.verticalSlider_9.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_9.setObjectName(_fromUtf8("verticalSlider_9"))
        self.label_39 = QtGui.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(620, 150, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_39.setFont(font)
        self.label_39.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.verticalSlider_10 = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_10.setGeometry(QtCore.QRect(580, 20, 28, 131))
        self.verticalSlider_10.setProperty("value", 50)
        self.verticalSlider_10.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_10.setObjectName(_fromUtf8("verticalSlider_10"))
        self.label_40 = QtGui.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(620, 110, 62, 20))
        self.label_40.setText(_fromUtf8(""))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.lcdNumber_8 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_8.setGeometry(QtCore.QRect(630, 60, 41, 21))
        self.lcdNumber_8.setObjectName(_fromUtf8("lcdNumber_8"))
        self.dial_14 = QtGui.QDial(self.centralwidget)
        self.dial_14.setGeometry(QtCore.QRect(610, 90, 50, 64))
        self.dial_14.setMinimum(-50)
        self.dial_14.setMaximum(50)
        self.dial_14.setObjectName(_fromUtf8("dial_14"))
        self.label_41 = QtGui.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(570, 150, 62, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(630, 390, 62, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_42 = QtGui.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(160, 520, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_42.setFont(font)
        self.label_42.setTextFormat(QtCore.Qt.LogText)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.dial_28 = QtGui.QDial(self.centralwidget)
        self.dial_28.setGeometry(QtCore.QRect(160, 460, 50, 64))
        self.dial_28.setProperty("value", 50)
        self.dial_28.setObjectName(_fromUtf8("dial_28"))
        self.lcdNumber_9 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_9.setGeometry(QtCore.QRect(470, 460, 41, 21))
        self.lcdNumber_9.setObjectName(_fromUtf8("lcdNumber_9"))
        self.lcdNumber_10 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_10.setGeometry(QtCore.QRect(470, 490, 41, 21))
        self.lcdNumber_10.setObjectName(_fromUtf8("lcdNumber_10"))
        self.lcdNumber_11 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_11.setGeometry(QtCore.QRect(870, 890, 41, 21))
        self.lcdNumber_11.setObjectName(_fromUtf8("lcdNumber_11"))
        self.lcdNumber_12 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_12.setGeometry(QtCore.QRect(610, 490, 41, 21))
        self.lcdNumber_12.setObjectName(_fromUtf8("lcdNumber_12"))
        self.lcdNumber_13 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_13.setGeometry(QtCore.QRect(610, 460, 41, 21))
        self.lcdNumber_13.setObjectName(_fromUtf8("lcdNumber_13"))
        self.dial_22 = QtGui.QDial(self.centralwidget)
        self.dial_22.setGeometry(QtCore.QRect(670, 490, 41, 61))
        self.dial_22.setObjectName(_fromUtf8("dial_22"))
        self.label_44 = QtGui.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(510, 170, 62, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(690, 160, 62, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_46 = QtGui.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(110, 150, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.label_47 = QtGui.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(110, 120, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.label_48 = QtGui.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(140, 100, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.label_49 = QtGui.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(180, 120, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.label_50 = QtGui.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(170, 150, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.label_51 = QtGui.QLabel(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(290, 120, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.label_52 = QtGui.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(360, 120, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.label_53 = QtGui.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(290, 150, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.label_54 = QtGui.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(350, 150, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.label_55 = QtGui.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(320, 100, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.dial_10 = QtGui.QDial(self.centralwidget)
        self.dial_10.setGeometry(QtCore.QRect(300, 110, 61, 61))
        self.dial_10.setMaximum(4)
        self.dial_10.setObjectName(_fromUtf8("dial_10"))
        self.label_56 = QtGui.QLabel(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(430, 110, 62, 20))
        self.label_56.setText(_fromUtf8(""))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.label_57 = QtGui.QLabel(self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(540, 150, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.label_58 = QtGui.QLabel(self.centralwidget)
        self.label_58.setGeometry(QtCore.QRect(480, 150, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.label_59 = QtGui.QLabel(self.centralwidget)
        self.label_59.setGeometry(QtCore.QRect(480, 120, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.label_60 = QtGui.QLabel(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(510, 100, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.dial_12 = QtGui.QDial(self.centralwidget)
        self.dial_12.setGeometry(QtCore.QRect(490, 110, 61, 61))
        self.dial_12.setMaximum(4)
        self.dial_12.setObjectName(_fromUtf8("dial_12"))
        self.label_61 = QtGui.QLabel(self.centralwidget)
        self.label_61.setGeometry(QtCore.QRect(540, 110, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.label_62 = QtGui.QLabel(self.centralwidget)
        self.label_62.setGeometry(QtCore.QRect(720, 100, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.dial_13 = QtGui.QDial(self.centralwidget)
        self.dial_13.setGeometry(QtCore.QRect(670, 100, 61, 61))
        self.dial_13.setMaximum(4)
        self.dial_13.setObjectName(_fromUtf8("dial_13"))
        self.label_63 = QtGui.QLabel(self.centralwidget)
        self.label_63.setGeometry(QtCore.QRect(660, 140, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_64 = QtGui.QLabel(self.centralwidget)
        self.label_64.setGeometry(QtCore.QRect(690, 90, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.label_65 = QtGui.QLabel(self.centralwidget)
        self.label_65.setGeometry(QtCore.QRect(660, 110, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.label_66 = QtGui.QLabel(self.centralwidget)
        self.label_66.setGeometry(QtCore.QRect(720, 140, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.label_67 = QtGui.QLabel(self.centralwidget)
        self.label_67.setGeometry(QtCore.QRect(710, 480, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.label_68 = QtGui.QLabel(self.centralwidget)
        self.label_68.setGeometry(QtCore.QRect(650, 480, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.label_69 = QtGui.QLabel(self.centralwidget)
        self.label_69.setGeometry(QtCore.QRect(680, 430, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.label_70 = QtGui.QLabel(self.centralwidget)
        self.label_70.setGeometry(QtCore.QRect(710, 440, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.label_71 = QtGui.QLabel(self.centralwidget)
        self.label_71.setGeometry(QtCore.QRect(680, 490, 62, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_71.setFont(font)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.label_43 = QtGui.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(610, 450, 62, 20))
        self.label_43.setText(_fromUtf8(""))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.dial_15 = QtGui.QDial(self.centralwidget)
        self.dial_15.setGeometry(QtCore.QRect(660, 440, 61, 61))
        self.dial_15.setMaximum(4)
        self.dial_15.setObjectName(_fromUtf8("dial_15"))
        self.label_72 = QtGui.QLabel(self.centralwidget)
        self.label_72.setGeometry(QtCore.QRect(650, 450, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.label_73 = QtGui.QLabel(self.centralwidget)
        self.label_73.setGeometry(QtCore.QRect(510, 450, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.dial_16 = QtGui.QDial(self.centralwidget)
        self.dial_16.setGeometry(QtCore.QRect(520, 440, 61, 61))
        self.dial_16.setMaximum(4)
        self.dial_16.setObjectName(_fromUtf8("dial_16"))
        self.label_74 = QtGui.QLabel(self.centralwidget)
        self.label_74.setGeometry(QtCore.QRect(510, 480, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.label_75 = QtGui.QLabel(self.centralwidget)
        self.label_75.setGeometry(QtCore.QRect(540, 500, 62, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.label_76 = QtGui.QLabel(self.centralwidget)
        self.label_76.setGeometry(QtCore.QRect(470, 450, 62, 20))
        self.label_76.setText(_fromUtf8(""))
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.dial_24 = QtGui.QDial(self.centralwidget)
        self.dial_24.setGeometry(QtCore.QRect(530, 490, 41, 61))
        self.dial_24.setObjectName(_fromUtf8("dial_24"))
        self.label_77 = QtGui.QLabel(self.centralwidget)
        self.label_77.setGeometry(QtCore.QRect(540, 430, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.dial_17 = QtGui.QDial(self.centralwidget)
        self.dial_17.setGeometry(QtCore.QRect(660, 440, 61, 61))
        self.dial_17.setMaximum(4)
        self.dial_17.setObjectName(_fromUtf8("dial_17"))
        self.label_78 = QtGui.QLabel(self.centralwidget)
        self.label_78.setGeometry(QtCore.QRect(710, 440, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.label_79 = QtGui.QLabel(self.centralwidget)
        self.label_79.setGeometry(QtCore.QRect(570, 480, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_79.setFont(font)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.label_80 = QtGui.QLabel(self.centralwidget)
        self.label_80.setGeometry(QtCore.QRect(570, 440, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Waree"))
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_80.setFont(font)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.verticalSlider_6, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.masterVol)
        QtCore.QObject.connect(self.dial_23, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.echoDecay)
        QtCore.QObject.connect(self.dial_25, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.echoDelay)
        QtCore.QObject.connect(self.dial_28, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.echoMix)
        QtCore.QObject.connect(self.dial_7, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.osc1Fine)
        QtCore.QObject.connect(self.dial_8, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.osc1Type)
        QtCore.QObject.connect(self.verticalSlider_7, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.osc1Vol)
        QtCore.QObject.connect(self.verticalSlider_8, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.osc2Vol)
        QtCore.QObject.connect(self.dial_11, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.osc3Fine)
        QtCore.QObject.connect(self.verticalSlider_9, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.osc3Vol)
        QtCore.QObject.connect(self.dial_14, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.osc4Fine)
        QtCore.QObject.connect(self.verticalSlider_10, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.osc4Vol)
        QtCore.QObject.connect(self.verticalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.A)
        QtCore.QObject.connect(self.verticalSlider_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.D)
        QtCore.QObject.connect(self.verticalSlider_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.V)
        QtCore.QObject.connect(self.verticalSlider_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.S)
        QtCore.QObject.connect(self.verticalSlider_5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.R)
        QtCore.QObject.connect(self.verticalSlider_11, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.P)
        QtCore.QObject.connect(self.dial_5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.filter1Cut)
        QtCore.QObject.connect(self.dial_6, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.filter1Angle)
        QtCore.QObject.connect(self.dial_26, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.filter2Cut)
        QtCore.QObject.connect(self.dial_27, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.filter2Angle)
        QtCore.QObject.connect(self.dial_9, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.osc2Fine)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), MainWindow.play)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.verticalSlider_7, self.dial_7)
        MainWindow.setTabOrder(self.dial_7, self.dial_8)
        MainWindow.setTabOrder(self.dial_8, self.verticalSlider_8)
        MainWindow.setTabOrder(self.verticalSlider_8, self.dial_9)
        MainWindow.setTabOrder(self.dial_9, self.verticalSlider_9)
        MainWindow.setTabOrder(self.verticalSlider_9, self.dial_11)
        MainWindow.setTabOrder(self.dial_11, self.verticalSlider_10)
        MainWindow.setTabOrder(self.verticalSlider_10, self.dial_14)
        MainWindow.setTabOrder(self.dial_14, self.dial_5)
        MainWindow.setTabOrder(self.dial_5, self.dial_6)
        MainWindow.setTabOrder(self.dial_6, self.dial_2)
        MainWindow.setTabOrder(self.dial_2, self.verticalSlider)
        MainWindow.setTabOrder(self.verticalSlider, self.verticalSlider_2)
        MainWindow.setTabOrder(self.verticalSlider_2, self.verticalSlider_3)
        MainWindow.setTabOrder(self.verticalSlider_3, self.verticalSlider_4)
        MainWindow.setTabOrder(self.verticalSlider_4, self.verticalSlider_5)
        MainWindow.setTabOrder(self.verticalSlider_5, self.verticalSlider_11)
        MainWindow.setTabOrder(self.verticalSlider_11, self.dial)
        MainWindow.setTabOrder(self.dial, self.dial_26)
        MainWindow.setTabOrder(self.dial_26, self.dial_27)
        MainWindow.setTabOrder(self.dial_27, self.dial_23)
        MainWindow.setTabOrder(self.dial_23, self.dial_25)
        MainWindow.setTabOrder(self.dial_25, self.dial_28)
        MainWindow.setTabOrder(self.dial_28, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.verticalSlider_6)
        MainWindow.setTabOrder(self.verticalSlider_6, self.dial_22)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Lfo 1", None))
        self.label_2.setText(_translate("MainWindow", "Lfo 2", None))
        self.label_3.setText(_translate("MainWindow", "master out", None))
        self.label_4.setText(_translate("MainWindow", "echo", None))
        self.label_5.setText(_translate("MainWindow", "filter", None))
        self.label_6.setText(_translate("MainWindow", "env", None))
        self.label_7.setText(_translate("MainWindow", "cross fade", None))
        self.label_8.setText(_translate("MainWindow", "low pass", None))
        self.label_9.setText(_translate("MainWindow", "osc 1", None))
        self.label_10.setText(_translate("MainWindow", "osc 2", None))
        self.label_11.setText(_translate("MainWindow", "osc 3", None))
        self.label_12.setText(_translate("MainWindow", "osc 4", None))
        self.pushButton.setText(_translate("MainWindow", "play", None))
        self.label_13.setText(_translate("MainWindow", "A", None))
        self.label_14.setText(_translate("MainWindow", "S", None))
        self.label_15.setText(_translate("MainWindow", "V", None))
        self.label_16.setText(_translate("MainWindow", "V", None))
        self.label_17.setText(_translate("MainWindow", "D", None))
        self.label_18.setText(_translate("MainWindow", "R", None))
        self.label_20.setText(_translate("MainWindow", "decay", None))
        self.label_21.setText(_translate("MainWindow", "delay", None))
        self.label_22.setText(_translate("MainWindow", "angle", None))
        self.label_23.setText(_translate("MainWindow", "cut-off", None))
        self.label_24.setText(_translate("MainWindow", "cut-off", None))
        self.label_27.setText(_translate("MainWindow", "P", None))
        self.label_28.setText(_translate("MainWindow", "cross fade", None))
        self.label_29.setText(_translate("MainWindow", "volume", None))
        self.label_30.setText(_translate("MainWindow", "type", None))
        self.label_31.setText(_translate("MainWindow", "fine", None))
        self.label_32.setText(_translate("MainWindow", "fine", None))
        self.label_33.setText(_translate("MainWindow", "type", None))
        self.label_35.setText(_translate("MainWindow", "volume", None))
        self.label_36.setText(_translate("MainWindow", "fine", None))
        self.label_38.setText(_translate("MainWindow", "volume", None))
        self.label_39.setText(_translate("MainWindow", "fine", None))
        self.label_41.setText(_translate("MainWindow", "volume", None))
        self.label_25.setText(_translate("MainWindow", "angle", None))
        self.label_42.setText(_translate("MainWindow", "mix", None))
        self.label_44.setText(_translate("MainWindow", "type", None))
        self.label_45.setText(_translate("MainWindow", "type", None))
        self.label_46.setText(_translate("MainWindow", "Sine", None))
        self.label_47.setText(_translate("MainWindow", "square", None))
        self.label_48.setText(_translate("MainWindow", "tri", None))
        self.label_49.setText(_translate("MainWindow", "saw", None))
        self.label_50.setText(_translate("MainWindow", "noise", None))
        self.label_51.setText(_translate("MainWindow", "square", None))
        self.label_52.setText(_translate("MainWindow", "saw", None))
        self.label_53.setText(_translate("MainWindow", "Sine", None))
        self.label_54.setText(_translate("MainWindow", "noise", None))
        self.label_55.setText(_translate("MainWindow", "tri", None))
        self.label_57.setText(_translate("MainWindow", "noise", None))
        self.label_58.setText(_translate("MainWindow", "Sine", None))
        self.label_59.setText(_translate("MainWindow", "square", None))
        self.label_60.setText(_translate("MainWindow", "tri", None))
        self.label_61.setText(_translate("MainWindow", "saw", None))
        self.label_62.setText(_translate("MainWindow", "saw", None))
        self.label_63.setText(_translate("MainWindow", "Sine", None))
        self.label_64.setText(_translate("MainWindow", "tri", None))
        self.label_65.setText(_translate("MainWindow", "square", None))
        self.label_66.setText(_translate("MainWindow", "noise", None))
        self.label_67.setText(_translate("MainWindow", "noise", None))
        self.label_68.setText(_translate("MainWindow", "Sine", None))
        self.label_69.setText(_translate("MainWindow", "tri", None))
        self.label_70.setText(_translate("MainWindow", "saw", None))
        self.label_71.setText(_translate("MainWindow", "type", None))
        self.label_72.setText(_translate("MainWindow", "square", None))
        self.label_73.setText(_translate("MainWindow", "square", None))
        self.label_74.setText(_translate("MainWindow", "Sine", None))
        self.label_75.setText(_translate("MainWindow", "type", None))
        self.label_77.setText(_translate("MainWindow", "tri", None))
        self.label_78.setText(_translate("MainWindow", "saw", None))
        self.label_79.setText(_translate("MainWindow", "noise", None))
        self.label_80.setText(_translate("MainWindow", "saw", None))

